---
title: "Collaborator Analysis"
format: html
editor: visual
---

# Authors

-   Andrew Uccello

## Exercise: Explore, Clean, and Wrangle Data
```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(here)
```
```{r}
lobster_traps <- read_csv(here::here("data/Lobster_Trap_Counts_All_Years_20210519.csv"))
```
```{r}
#Convert -99999 to NA
unique(lobster_traps$TRAPS)
traps_clean <- lobster_traps %>%
  mutate(TRAPS = na_if(TRAPS, -99999))
unique(traps_clean$TRAPS)
```
```{r}
traps_no_naples <- traps_clean %>%
  filter(SITE != "NAPL")
unique(traps_no_naples$SITE)
```
```{r}
traps_carp20 <- traps_clean %>%
  filter(SITE == "CARP") %>%
  filter(TRAPS > 20)
```
```{r}
traps_max_floats <- traps_clean %>%
  group_by(SITE, MONTH) %>%
  summarise(max_traps = max(TRAPS, na.rm = TRUE))
  
```
## Exercise: Data Visualization

```{r}
#Histogram
  ggplot(traps_clean, aes(x = TRAPS)) +
  geom_histogram() +
  facet_wrap(~ YEAR)

```
```{r}
lobsters_traps_summarize <-
  traps_clean %>%
  group_by(SITE,YEAR) %>%
  mutate(TOTAL_TRAPS = sum(TRAPS, na.rm = TRUE))

ggplot(lobsters_traps_summarize, aes(x = YEAR, y = TOTAL_TRAPS)) +
  geom_line(aes(color = SITE)) +
  geom_point(aes(colour = SITE))
```

```{r}
lobster_traps_fishing_pressure <- traps_clean %>%
  filter(YEAR = c("2019","2020","2021")) %>%
  mutate(FISHING_PRESSURE = if_else(condition = ))


```

